import { Injectable, Logger } from '@nestjs/common';
import { GoogleGenAI } from '@google/genai';
import { extractErrorMessage } from '@shared/utils';
import type { IImageGenerator } from '../../domain/services/image-generator.interface';

const IMAGEN_MODEL = 'imagen-4.0-fast-generate-001';
const IMAGE_ASPECT_RATIO = '16:9';
const LOG_PROMPT_PREFIX_LENGTH = 100;

const COLOR_PALETTE = 'blue, dark navy and white color palette';
const STYLE_SUFFIX = `2D corporate flat vector illustration, editorial style, minimalist, tech company vibe, ${COLOR_PALETTE}, clean solid pastel background, high quality, highly detailed.`;
const AVOID_SUFFIX =
  'Absolutely NO realistic photos, NO 3D renders, NO text, NO letters, NO words, NO watermarks.';

@Injectable()
export class Imagen3ImageGeneratorService implements IImageGenerator {
  private readonly logger = new Logger(Imagen3ImageGeneratorService.name);
  private readonly client: GoogleGenAI;

  constructor() {
    this.client = new GoogleGenAI({
      vertexai: true,
      project: process.env.GCP_PROJECT_ID,
      location: process.env.GCP_LOCATION ?? 'europe-west1',
    });
  }

  async generateImage(prompt: string): Promise<Buffer> {
    const styledPrompt = `${prompt}. ${STYLE_SUFFIX} ${AVOID_SUFFIX}`;

    this.logger.log(
      `Generating image: "${styledPrompt.substring(0, LOG_PROMPT_PREFIX_LENGTH)}..."`,
    );

    try {
      const response = await this.client.models.generateImages({
        model: IMAGEN_MODEL,
        prompt: styledPrompt,
        config: { numberOfImages: 1, aspectRatio: IMAGE_ASPECT_RATIO },
      });

      const images = response.generatedImages ?? [];
      if (images.length === 0 || !images[0].image?.imageBytes) {
        throw new Error('No image generated by Imagen 3');
      }

      const buffer = Buffer.from(images[0].image.imageBytes, 'base64');
      this.logger.log(`Image generated: ${buffer.length} bytes`);
      return buffer;
    } catch (error: unknown) {
      const message = extractErrorMessage(error);
      if (message.includes('No image generated')) throw error as Error;
      this.logger.error(`Image generation failed: ${message}`);
      throw new Error(`Image generation failed: ${message}`);
    }
  }
}
