import { Injectable, Logger } from '@nestjs/common';
import { GoogleGenAI } from '@google/genai';
import { extractErrorMessage } from '@shared/utils';
import type { IImageGenerator } from '../../domain/services/image-generator.interface';

const IMAGEN_MODEL = 'imagen-4.0-fast-generate-001';
const IMAGE_ASPECT_RATIO = '16:9';
const LOG_PROMPT_PREFIX_LENGTH = 100;

const COLOR_PALETTE = 'blue, dark navy and white color palette';
const STYLE_SUFFIX = `2D corporate flat vector illustration, editorial style, minimalist, tech company vibe, ${COLOR_PALETTE}, clean solid pastel background, high quality, highly detailed.`;
const AVOID_SUFFIX =
  'Absolutely NO realistic photos, NO 3D renders, NO text, NO letters, NO words, NO watermarks.';

/**
 * Vertex AI Imagen quota for this project:
 *  - 5 requests per minute (RPM), sliding window
 *  - 1 concurrent request (no parallelism)
 */
const RPM_LIMIT = 5;
const RPM_WINDOW_MS = 60_000;
const RPM_COOLDOWN_BUFFER_MS = 2_000;
const RETRY_429_WAIT_MS = 62_000;
const MAX_429_RETRIES = 3;
const MS_PER_SECOND = 1_000;

@Injectable()
export class Imagen3ImageGeneratorService implements IImageGenerator {
  private readonly logger = new Logger(Imagen3ImageGeneratorService.name);
  private readonly client: GoogleGenAI;
  private readonly requestTimestamps: number[] = [];

  constructor() {
    this.client = new GoogleGenAI({
      vertexai: true,
      project: process.env.GCP_PROJECT_ID,
      location: process.env.GCP_LOCATION ?? 'europe-west1',
    });
  }

  async generateImage(prompt: string): Promise<Buffer> {
    const styledPrompt = `${prompt}. ${STYLE_SUFFIX} ${AVOID_SUFFIX}`;

    this.logger.log(
      `Generating image: "${styledPrompt.substring(0, LOG_PROMPT_PREFIX_LENGTH)}..."`,
    );

    for (let attempt = 0; attempt <= MAX_429_RETRIES; attempt++) {
      await this.waitForRateLimit();
      this.recordRequest();

      try {
        const response = await this.client.models.generateImages({
          model: IMAGEN_MODEL,
          prompt: styledPrompt,
          config: { numberOfImages: 1, aspectRatio: IMAGE_ASPECT_RATIO },
        });

        const images = response.generatedImages ?? [];
        if (images.length === 0 || !images[0].image?.imageBytes) {
          throw new Error('No image generated by Imagen');
        }

        const buffer = Buffer.from(images[0].image.imageBytes, 'base64');
        this.logger.log(`Image generated: ${buffer.length} bytes`);
        return buffer;
      } catch (error: unknown) {
        const message = extractErrorMessage(error);

        if (this.isRateLimitError(message) && attempt < MAX_429_RETRIES) {
          this.logger.warn(
            `Rate limited (429) on attempt ${attempt + 1}/${MAX_429_RETRIES + 1} — waiting ${RETRY_429_WAIT_MS / MS_PER_SECOND}s before retry`,
          );
          await this.sleep(RETRY_429_WAIT_MS);
          continue;
        }

        if (message.includes('No image generated')) throw error as Error;
        this.logger.error(`Image generation failed: ${message}`);
        throw new Error(`Image generation failed: ${message}`);
      }
    }

    throw new Error(
      'Image generation failed: max retries exhausted on rate limit',
    );
  }

  private async waitForRateLimit(): Promise<void> {
    this.pruneOldTimestamps();

    if (this.requestTimestamps.length >= RPM_LIMIT) {
      const oldestInWindow = this.requestTimestamps[0];
      const waitMs =
        RPM_WINDOW_MS - (Date.now() - oldestInWindow) + RPM_COOLDOWN_BUFFER_MS;

      if (waitMs > 0) {
        this.logger.warn(
          `RPM limit reached (${RPM_LIMIT}/min), pausing ${Math.ceil(waitMs / MS_PER_SECOND)}s`,
        );
        await this.sleep(waitMs);
        this.pruneOldTimestamps();
      }
    }
  }

  private recordRequest(): void {
    this.requestTimestamps.push(Date.now());
  }

  private pruneOldTimestamps(): void {
    const cutoff = Date.now() - RPM_WINDOW_MS;
    while (
      this.requestTimestamps.length > 0 &&
      this.requestTimestamps[0] <= cutoff
    ) {
      this.requestTimestamps.shift();
    }
  }

  private isRateLimitError(message: string): boolean {
    return (
      message.includes('429') ||
      message.includes('RESOURCE_EXHAUSTED') ||
      message.includes('Quota exceeded')
    );
  }

  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
